apiVersion: v1
kind: Service
metadata:
  name: my-service
  name: project1
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80           # Service port
      targetPort: 8080   # Pod container port
  type: ClusterIP       # default, can be omitted
