apiVersion: v1
kind: Pod
metadata:
  name: nginx-public
  namespace: project1
spec:
  containers:
  - name: nginx
    image: nginx:latest # public image from Docker Hub
    ports:
    - containerPort: 80
