#Create Nginx-server 
apiVersion: v1
kind: Pod
metadata:
  name: nginx-private
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx:latest # public image from Docker Hub
    ports:
    - containerPort: 80
